pluginManagement {
    repositories {
        // 使用阿里云镜像加速插件下载
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'playerDoll-neoForge-1.21.1'

// 包含兼容模块
include 'player-doll-customskinloader-compat'
project(':player-doll-customskinloader-compat').projectDir = file('../player-doll-customskinloader-compat')

